**Sorting**

1. sort() for 1D
2. sort() for 2D , using axis=0->cols,axis=1->rows

In [3]:
#Example 1 (1D)

import numpy as np
# arr=np.array([10,20,56,365,2,1])
# print(arr)
# arr_s=np.sort(arr)
# print(arr_s)

#Exapmle 2 (2D)
# arr1=np.array([[12,3,22],[34,23,2]])
# print(arr1)
# arr2=np.sort(arr1,axis=0)# for column wise sorting
# print("<--------->")

# print(arr2)
# print("<--------->")
# arr2=np.sort(arr1)#(by Default row wise sorting)
# print(arr2)



#Example 3
arr1=np.array([3,1,12,3,22])
print(arr1)
arr2=np.sort(arr1)# for column wise sorting
print("<--------->")

print(arr2)
print("<--------->")
arr2=np.sort(arr1)#(by Default row wise sorting)
print(arr2)

[ 3  1 12  3 22]
<--------->
[ 1  3  3 12 22]
<--------->
[ 1  3  3 12 22]


In [4]:
#Filter
import numpy as np
arr=np.array([10,20,40,6,3,4,2])
print(arr)
arr_f=arr[arr<40]
print("arr_f: ",arr_f)



#Example 2.
arr_f1=arr[arr%2==0]
print("arrf1:",arr_f1)

[10 20 40  6  3  4  2]
arr_f:  [10 20  6  3  4  2]
arrf1: [10 20 40  6  4  2]


In [5]:
#Fancy indexing
import numpy as np
# arr=np.array([10,20,30,2,3,1])
# print(arr)
# arr_f=arr[[2,3]]#[i1,i2](i1,i2 wo index hae jis index ki value chaiye)
# print(arr_f)



#Example 2.(in sorted fashion)
# arr=np.array([10,20,30,2,3,1])
# print(arr)
# arr_f=np.sort(arr[[2,3]])#[i1,i2](i1,i2 wo index hae jis index ki value chaiye)
# print(arr_f)



# Example 3.
# arr=np.array([10,20,30,2,3,1])
# print(arr)
# arr_f=np.sort(arr[[2,3]])[np.sort(arr[[2,3]])>15]#[i1,i2](i1,i2 wo index hae jis index ki value chaiye)
# print(arr_f)

#Exapmle 3.2
arr=np.array([[10,20,12,11,9,2],[6,7,45,67,334,78]])
# print(arr)
arr_f=arr[[1],[2]]
print(arr_f)



#np.Where

#Example 4.
# arr=np.array([10,20,12,11,9,2])
# print(arr)
# arr_f=np.where(arr>10,"True","false")#Condition : True : False
# print(arr_f)





#Example 5.
# arr=np.array([10,20,12,11,9,2])
# print(arr)
# arr_f=np.where(arr>10,arr+2,arr-2)#Condition : True : False
# print(arr_f)



#Example 6.
# arr=np.array([10,20,12,11,9,2])
# print(arr)
# arr_f=np.where(arr>18,"valid voter","invalid user")#Condition : True : False
# print(arr_f)



[45]


In [7]:
import numpy as np
# arr1=np.array([10,20,30,34])
# arr2=np.array([2,34,32,12])
# #Concatination method
# arr1_arr2=arr1+arr2#not a right method
# print(arr1_arr2)
# #manually
# arr1_arr2=np.concatenate((arr1,arr2),)
# print(arr1_arr2)




#for 2D array

arr1=np.array([[10,20,30,34],[12,65,33,45]])

arr2=np.array([[2,34,32,12],[23,45,63,90]])
#Concatination method
arr1_arr2=arr1+arr2#not a right method
print(arr1_arr2)
print("------------------------")
#manually
arr1_arr2=np.concatenate((arr1,arr2))
print(arr1_arr2)
print("-------------")
arr1_arr2=np.concatenate((arr1,arr2),axis=0)
print(arr1_arr2)





[[ 12  54  62  46]
 [ 35 110  96 135]]
------------------------
[[10 20 30 34]
 [12 65 33 45]
 [ 2 34 32 12]
 [23 45 63 90]]
-------------
[[10 20 30 34]
 [12 65 33 45]
 [ 2 34 32 12]
 [23 45 63 90]]
